# Generated by Django 5.1.4 on 2025-02-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_address_customuser_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
