# Generated by Django 5.1.4 on 2024-12-22 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать от 7 до 15 цифр (может включать +).', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
