# Generated by Django 5.1.4 on 2024-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_product_image_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_item_images/'),
        ),
    ]
