# Generated by Django 5.1.4 on 2025-02-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
